<?xml version="1.0" encoding="utf-8"?><Database Name="chart" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0Q1NNVL;Initial Catalog=chart;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="chartConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCategory" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumberArticle" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCategory" Member="tblCategory1s">
    <Type Name="tblCategory1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumberArticle" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblJob" Member="tblJobs">
    <Type Name="tblJob">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AspNet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>